// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vision.SecurityOperationsService.Infrastructure.Persistence;

#nullable disable

namespace Vision.SecurityOperationsService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SecurityOperationsDbContext))]
    [Migration("20260811015935_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("security_operations")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.HasIndex("HospitalId")
                        .HasDatabaseName("ix_buildings_hospital_id");

                    b.HasIndex("HospitalId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_buildings_hospital_id_name");

                    b.ToTable("buildings", "security_operations");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Hospital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_hospitals");

                    b.ToTable("hospitals", "security_operations");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Floor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("floor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_locations_building_id");

                    b.HasIndex("BuildingId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_building_id_name");

                    b.ToTable("locations", "security_operations");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.SecurityAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_tag");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("LastServiceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_service_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_security_assets");

                    b.HasIndex("AssetTag")
                        .IsUnique()
                        .HasDatabaseName("ix_security_assets_asset_tag")
                        .HasFilter("asset_tag IS NOT NULL");

                    b.HasIndex("AssetType")
                        .HasDatabaseName("ix_security_assets_asset_type");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_security_assets_location_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_security_assets_status");

                    b.HasIndex("Status", "AssetType")
                        .HasDatabaseName("ix_security_assets_status_asset_type");

                    b.ToTable("security_assets", "security_operations");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.SecurityIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_summary");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("SecurityAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_asset_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_security_incidents");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_security_incidents_created_at");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_security_incidents_location_id");

                    b.HasIndex("SecurityAssetId")
                        .HasDatabaseName("ix_security_incidents_security_asset_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_security_incidents_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_security_incidents_status");

                    b.HasIndex("WorkOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_security_incidents_work_order_id")
                        .HasFilter("work_order_id IS NOT NULL");

                    b.HasIndex("Status", "Severity")
                        .HasDatabaseName("ix_security_incidents_status_severity");

                    b.ToTable("security_incidents", "security_operations");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", "security_operations");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Building", b =>
                {
                    b.HasOne("Vision.SecurityOperationsService.Domain.Hospital", "Hospital")
                        .WithMany("Buildings")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_buildings_hospitals_hospital_id");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Location", b =>
                {
                    b.HasOne("Vision.SecurityOperationsService.Domain.Building", "Building")
                        .WithMany("Locations")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_buildings_building_id");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.SecurityAsset", b =>
                {
                    b.HasOne("Vision.SecurityOperationsService.Domain.Location", "Location")
                        .WithMany("SecurityAssets")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_assets_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.SecurityIncident", b =>
                {
                    b.HasOne("Vision.SecurityOperationsService.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_incidents_locations_location_id");

                    b.HasOne("Vision.SecurityOperationsService.Domain.SecurityAsset", "SecurityAsset")
                        .WithMany("Incidents")
                        .HasForeignKey("SecurityAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_security_incidents_security_assets_security_asset_id");

                    b.Navigation("Location");

                    b.Navigation("SecurityAsset");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Building", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Hospital", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.Location", b =>
                {
                    b.Navigation("SecurityAssets");
                });

            modelBuilder.Entity("Vision.SecurityOperationsService.Domain.SecurityAsset", b =>
                {
                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
