// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vision.WorkOrderService.Infrastructure.Persistence;

#nullable disable

namespace Vision.WorkOrderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkOrderDbContext))]
    [Migration("20260815185323_AddWorkOrderIndexes")]
    partial class AddWorkOrderIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("work_orders")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vision.WorkOrderService.Domain.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CognitoSubject")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cognito_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.HasKey("Id")
                        .HasName("pk_technicians");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_technicians_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_technicians_is_active");

                    b.ToTable("technicians", "work_orders");
                });

            modelBuilder.Entity("Vision.WorkOrderService.Domain.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetNameSnapshot")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("asset_name_snapshot");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedTechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("completion_summary");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("LocationNameSnapshot")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location_name_snapshot");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("SecurityAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_asset_id");

                    b.Property<Guid?>("SecurityIncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_incident_id");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("AssignedTechnicianId")
                        .HasDatabaseName("ix_work_orders_assigned_technician_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_work_orders_created_at");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_work_orders_priority");

                    b.HasIndex("SecurityAssetId")
                        .HasDatabaseName("ix_work_orders_security_asset_id");

                    b.HasIndex("SecurityIncidentId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_orders_security_incident_id")
                        .HasFilter("security_incident_id IS NOT NULL");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_orders_source_event_id")
                        .HasFilter("source_event_id IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_orders_status");

                    b.ToTable("work_orders", "work_orders");
                });

            modelBuilder.Entity("Vision.WorkOrderService.Domain.WorkOrder", b =>
                {
                    b.HasOne("Vision.WorkOrderService.Domain.Technician", "AssignedTechnician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_orders_technicians_assigned_technician_id");

                    b.OwnsMany("Vision.WorkOrderService.Domain.TechnicianNote", "Notes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("content");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("TechnicianId")
                                .HasColumnType("uuid")
                                .HasColumnName("technician_id");

                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("work_order_id");

                            b1.HasKey("Id")
                                .HasName("pk_technician_notes");

                            b1.HasIndex("WorkOrderId")
                                .HasDatabaseName("ix_technician_notes_work_order_id");

                            b1.ToTable("technician_notes", "work_orders");

                            b1.WithOwner("WorkOrder")
                                .HasForeignKey("WorkOrderId")
                                .HasConstraintName("fk_technician_notes_work_orders_work_order_id");

                            b1.Navigation("WorkOrder");
                        });

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Vision.WorkOrderService.Domain.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
